### ISSUE TITLE
NDK toolchain is not downloaded as part of SDK

### ISSUE THREAD

**Issue by ranjankumar23** [quittle/gradle-setup-android-sdk#16]
Thanks for your plugin for developer community.

I see that NDK toolchain is not downloaded as part of SDK.

If you have time then please work on it. If it is ok with you then i would like to give it a try to work on this issue.

**Comment by quittle** [comment]
Hey, .I'm a bit busy with other things at the moment, but I'd be happy to take this as a pull request. If you want to add this, could you update the extension to take a map that is the SDK tools to versions that should be installed? Unlike the Android SDK version, I don't think there's good way to guess what version is required. Hard-coding the value in the plugin makes upgrades difficult and having a specific key for the NDK and its common dependencies is not extensible so if want to add support for the NDK, I'd appreciate if you add it in a generic way.

**Comment by quittle** [comment]
I'm taking a look into it now

**Comment by quittle** [comment]
This should be supported in plugin version `1.3.0`, which should be published soon. Let me know if the new `packages` methos in the plugin extension works sufficiently for you. I will update the documentation later, explaining how to use it.

**Comment by quittle** [comment]
I have updated the README to cover this addition to the Gradle extension.
