### ISSUE TITLE
The path of sdkmanager has changed

### ISSUE THREAD

**Issue by bonitao** [quittle/gradle-setup-android-sdk#167]
See https://stackoverflow.com/a/61176718 and https://stackoverflow.com/a/60598900 for the details. But basically, for the new versions of the android sdk the path in https://github.com/quittle/gradle-setup-android-sdk/blob/000c844c1ad65c2e39693d470d1131c6060777c8/setup-android-sdk/src/main/java/com/quittle/setupandroidsdk/SetupAndroidSdkPlugin.java#L104 needs to change from "tools/bin/sdkmanager" to "cmdline-tools/bin/sdkmanager".

Same for https://github.com/quittle/gradle-setup-android-sdk/blob/000c844c1ad65c2e39693d470d1131c6060777c8/setup-android-sdk/src/main/java/com/quittle/setupandroidsdk/SetupAndroidSdkPlugin.java#L106.

**Comment by quittle** [comment]
Version `3.1.0` of the plugin should release shortly with this update. Can you please try it out and let me know if it works the way you wanted?

**Comment by quittle** [comment]
@bonitao Hey, just following up to see if you can confirm the latest release fixes the issue you were facing.

**Comment by bonitao** [comment]
Hi @quittle ,

I confirm this is now fixed. Thanks a lot!
