### ISSUE TITLE
I try this on github actions, got sdkmanager not found

### ISSUE THREAD

**Issue by FrozzDay** [quittle/gradle-setup-android-sdk#199]
I got something like this

>  Unable to run sdkmanager successfully. Exit code: 1
i tried to add to the PATH with `export PATH="$PATH:/usr/local/lib/android/sdk/cmdline-tools/7.0/bin"` but no difference
 my current solution is using https://github.com/android-actions/setup-android and remove the plugin

**Comment by quittle** [comment]
Can you run your build with `--debug` and provide the output? It's hard to diagnose with just the short message you attached

**Comment by FrozzDay** [comment]
I'm sorry, i mean that i use this plugin with github actions to help setup android sdk, but it seem that sdkmanager isn't part of it(?). So i tried another way to help setup android sdk in github actions. I'm gonna close this issue as it different platform
