### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by developernotes** [quittle/gradle-setup-android-sdk#200]
Hi @quittle,

This Gradle plugin looks quite helpful, however, I ran into an couple of issues integrating it while working on macOS. At first, I utilized the following setup:

```
setupAndroidSdk {
  sdkToolsVersion '11076708'
  packages 'cmdline-tools;android-34;default;x86'
}
```

Which produced the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'codebook-android-temp'.
> Failed to notify project evaluation listener.
   > Unable read Android SDK tools zip
      > https://dl.google.com/android/repository/commandlinetools-linux-11076708.zip
   > Cannot invoke "java.io.File.getAbsolutePath()" because "sdkManager" is null
```

It appears the URL for this package should contain `_latest` (i.e., [example of latest URL from Google](dl.google.com/android/repository/commandlinetools-mac-11076708_latest.zip)). Additionally, the plugin appears to be identifying the host as Linux, instead of macOS. I suspect this is due to the logic [here](https://github.com/quittle/gradle-setup-android-sdk/blob/main/setup-android-sdk/src/main/java/com/quittle/setupandroidsdk/SetupAndroidSdkPlugin.java#L221-L234) where `Os.isFamily(Os.FAMILY_UNIX)` returns `true` for macOS. This might be resolved by changing the order of the check to include `Os.isFamily(Os.FAMILY_MAC)` before `Os.isFamily(Os.FAMILY_UNIX)`. Would it be possible to get this changed, possibly through a pull request, or a future release? Thanks!

**Comment by quittle** [comment]
Yeah, feel free to put up a pull request and I'll have a look. I don't actively maintain this plugin but am happy to keep it running. It doesn't take much to maintain anyways since it's just occasional URLs that update

**Comment by developernotes** [comment]
Hi @quittle,

I just wanted to follow-up with you on this. We no longer have a need for this plugin currently so I am not planning on sending over a pull request for macOS support at this time. Thanks.
