### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by chavdarb** [quittle/gradle-setup-android-sdk#42]
Upon executing the build it fails:
> sdkmanager failed to run successfully
   > Cannot run program "C:\Work\paysafe-wallet-user-events-library\build\android-sdk-root\tools\bin\sdkmanager": CreateProcess error=2, The system cannot find the file specified

It seems for windows "sdkmanager.bat" is being downloaded, but can not be executed. So some logic must be added to support sdkmanager for windows.

**Comment by quittle** [comment]
Ah, interesting. I will take a look into this. I suspect this will be an issue for a number of tools being run.

**Comment by quittle** [comment]
I have created ff3dfd924d4f9bef450a7e98ce837d562cdcc09c to support windows batch files. I'm not sure if there are any particular issues with install the Android NDK as I could get `ndk-bundle` to install but kept getting errors when linking the C++ code against linux based libraries. If you have any insights into NDK-related issues and how to fix it, I'd very much appreciate it. I will bump the version of the plugin to 1.4.0 if the current build passes.

**Comment by quittle** [comment]
@chavdarb have you had a chance to check if this fixed your issue?

**Comment by quittle** [comment]
Resolving this issue as fixed. If the new version of the plugin doesn't work, feel free to re-open. I'll be happy to take another look
